const qs=[
 ['01','Can I drink the water?','Not by default. Condensate can pass through treatment, but drinking-water suitability depends on the configured pathway, local requirements, sampling and verification for the intended use.'],
 ['02','How much can it produce?','There is no single honest number for every site. Production depends on temperature, relative humidity, system configuration, airflow, surface performance and operating strategy. A site assessment and measured pilot are the appropriate path to a useful range.'],
 ['03','What happens when humidity falls?','The dew point falls and condensation potential usually decreases. The system may produce less water, require a different operating strategy, or reach conditions where operation is not useful.'],
 ['04','How much energy does it use?','Energy intensity must be measured for the actual system and conditions. This site intentionally does not publish a validated kWh/L figure without supporting data.'],
 ['05','Is the device finished?','The hardware imagery on this site is concept visualization. It communicates system direction, not proof of a finalized production device unless later evidence explicitly says otherwise.'],
 ['06','What does a pilot prove?','A pilot can measure local climate behavior, production, energy intensity, treatment performance, maintenance demands and evidence gaps. It cannot prove universal performance everywhere.']
] as const
export function HardQuestions(){return <section className="questions section section--light" aria-labelledby="questions-title"><div className="container questions__grid" data-reveal><div><p className="kicker">Hard questions / 09</p><h2 id="questions-title" className="display display--md">No hidden<br/>conditions.</h2></div><div className="questions__list">{qs.map(([i,q,a],n)=><details key={i} open={n===0}><summary><span className="mono">{i}</span><strong>{q}</strong><i aria-hidden="true">+</i></summary><p>{a}</p></details>)}</div></div></section>}
